export type GovernanceErrorCode =
  | "INSTITUTION_NOT_FOUND"
  | "INSTITUTION_STATE_CONFLICT"
  | "ORGANIZATIONAL_UNIT_INVALID"
  | "GOVERNANCE_MANDATE_NOT_FOUND"
  | "GOVERNANCE_MANDATE_STATE_CONFLICT"
  | "GOVERNANCE_MANDATE_INVALID"
  | "MANDATE_RESOLUTION_FAILED"
  | "MANDATE_CONTEXT_INSUFFICIENT"
  | "GOVERNANCE_ADMIN_SCOPE_INSUFFICIENT"
  | "GOVERNANCE_SELF_ESCALATION"
  | "AUTHORITY_DELEGATION_NOT_FOUND"
  | "DELEGATION_SCOPE_EXPANSION"
  | "AUTHORITY_DELEGATION_CYCLE"
  | "DELEGATION_DEPTH_EXCEEDED"
  | "DELEGATION_STATE_CONFLICT"
  | "DELEGATION_EXPIRED"
  | "DELEGATION_SOURCE_AUTHORITY_MISSING"
  | "GOVERNANCE_ADMIN_CANNOT_MINT_OPERATIONAL_AUTHORITY"
  | "AUTHORITY_DENIED"
  | "AUTHORITY_CONDITIONAL"
  | "GOVERNANCE_CASE_NOT_FOUND"
  | "GOVERNANCE_CASE_STATE_CONFLICT"
  | "GOVERNANCE_CASE_EXPIRED"
  | "GOVERNANCE_ATTESTATION_INVALID"
  | "GOVERNANCE_ATTESTATION_REPLAY"
  | "GOVERNANCE_ATTESTATION_EXPIRED"
  | "GOVERNANCE_CROSS_CASE_ATTESTATION"
  | "GOVERNANCE_QUORUM_PENDING"
  | "GOVERNANCE_QUORUM_BLOCKED"
  | "SEPARATION_OF_DUTIES_VIOLATION"
  | "APPROVAL_LAUNDERING"
  | "GOVERNANCE_PROOF_NOT_FOUND"
  | "GOVERNANCE_PROOF_REQUIRED"
  | "GOVERNANCE_PROOF_SUBJECT_MISMATCH"
  | "GOVERNANCE_PROOF_STALE"
  | "GOVERNANCE_PROOF_EXPIRED"
  | "AUTHORITY_REVOCATION_INVALID"
  | "GOVERNANCE_HOLD_ACTIVE"
  | "GOVERNANCE_HOLD_NOT_FOUND"
  | "GOVERNANCE_HOLD_SCOPE_INSUFFICIENT"
  | "GOVERNANCE_HOLD_OPERATOR_SCOPE_INSUFFICIENT"
  | "GOVERNANCE_VERSION_CONFLICT"
  | "GOVERNANCE_CAS_CONFLICT"
  | "CONSTITUTIONAL_MUTATION_BYPASS_DENIED";

export class GovernanceError extends Error {
  readonly code: GovernanceErrorCode;
  readonly details?: Record<string, unknown>;

  constructor(
    code: GovernanceErrorCode,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "GovernanceError";
    this.code = code;
    if (details !== undefined) this.details = details;
  }
}

export function isGovernanceError(error: unknown): error is GovernanceError {
  return error instanceof GovernanceError;
}
