export const DECISION_POLICY_ERROR_CODES = [
  "DECISION_CONTEXT_NOT_FOUND",
  "DECISION_CONTEXT_INVALID",
  "DECISION_POLICY_NOT_FOUND",
  "DECISION_POLICY_VERSION_CONFLICT",
  "DECISION_POLICY_STATE_CONFLICT",
  "DECISION_POLICY_CAS_CONFLICT",
  "INVALID_DECISION_POLICY_TRANSITION",
  "DECISION_PREDICATE_INVALID",
  "DECISION_PREDICATE_ARBITRARY_CODE_REJECTED",
  "DECISION_ACTION_INELIGIBLE",
  "DECISION_RULE_CONFLICT",
  "DECISION_POLICY_VALIDATION_FAILED",
  "DECISION_DEFAULT_ACTION_REQUIRED",
  "DECISION_COUNTERFACTUAL_UNSUPPORTED",
  "DECISION_POLICY_APPROVER_SCOPE_INSUFFICIENT",
  "DECISION_POLICY_ACTIVATOR_SCOPE_INSUFFICIENT",
  "DECISION_POLICY_APPROVAL_INVALID",
  "DECISION_POLICY_APPROVAL_EXPIRED",
  "DECISION_POLICY_ACTIVATION_INVALID",
  "DECISION_POLICY_ACTIVATION_EXPIRED",
  "ACTIVATION_NOT_READY",
  "DECISION_POLICY_NOT_ACTIVE",
  "DECISION_STATE_INSUFFICIENT",
  "DECISION_STATE_STALE",
  "DECISION_STATE_SCOPE_MISMATCH",
  "DECISION_STATE_UNIT_MISMATCH",
  "DECISION_GOVERNANCE_DRIFT",
  "DECISION_CAUSAL_EVIDENCE_STALE",
  "DECISION_CAUSAL_EVIDENCE_NOT_SUPPORTED",
  "DECISION_RECOMMENDATION_INVALID",
  "DECISION_DOWNSTREAM_PORT_UNAVAILABLE",
  "DECISION_MATERIALIZATION_NOT_PERMITTED",
  "DECISION_BUDGET_EXCEEDED",
  "PACKAGE_STALE",
  "DATABASE_UNAVAILABLE",
] as const;

export type DecisionPolicyErrorCode =
  (typeof DECISION_POLICY_ERROR_CODES)[number];

export class DecisionPolicyError extends Error {
  readonly code: DecisionPolicyErrorCode;
  readonly details?: Record<string, unknown> | undefined;

  constructor(
    code: DecisionPolicyErrorCode,
    message: string,
    details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "DecisionPolicyError";
    this.code = code;
    if (details !== undefined) {
      this.details = details;
    }
  }
}

export function isDecisionPolicyError(
  error: unknown,
): error is DecisionPolicyError {
  return error instanceof DecisionPolicyError;
}
